# -*- coding: utf-8 -*-
"""EDA_Week02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LvUzMlbwCN2nR49dBIE14MvSEOhnLvfX
"""

import pandas as pd
#creating pandas series with indexes
data = pd.Series([1, 4, 9, 6, 7], index=['a', 'x', 'c', '2', 'e'])
print(data)

import pandas as pd
#creating a dictionary
data = {"Bilal": 42, "Ayesha": 38, "Hadia": 39}
#creating pandas series from dictionary
df = pd.Series(data)
print(df)

import pandas as pd
#creating dictionary
data = {
    "day": ["1/1/2017", "1/2/2017", "1/3/2017", "1/4/2017", "1/5/2017", "1/6/2017"],
    "temperature": [32, 35, 28, 24, 32, 31],
    "windspeed": [1, 2, 6, 7, 4, 2],
    "event": ["Sunny", "Sunny", "Rain", "Snow", "Rain", "Sunny"]
}
#creating dataFrame from the dictionary
df = pd.DataFrame(data)
print(df)

import pandas as pd
#creating dictionary
data = {
    "day": ["1/1/2017", "1/2/2017", "1/3/2017", "1/4/2017", "1/5/2017", "1/6/2017"],
    "temperature": [32, 35, 28, 24, 32, 31],
    "windspeed": [1, 2, 6, 7, 4, 2],
    "event": ["Sunny", "Sunny", "Rain", "Snow", "Rain", "Sunny"]
}
#creating dataFrame from the dictionary
df = pd.DataFrame(data)
#setting index to ['a','b','c','d','e','f']
df.index = ['a', 'b', 'c', 'd', 'e', 'f']
print(df)

import pandas as pd
#creating dictionary
data = {
    "day": ["1/1/2017", "1/2/2017", "1/3/2017", "1/4/2017", "1/5/2017", "1/6/2017"],
    "temperature": [32, 35, 28, 24, 32, 31],
    "windspeed": [1, 2, 6, 7, 4, 2],
    "event": ["Sunny", "Sunny", "Rain", "Snow", "Rain", "Sunny"]
}
#creating dataFrame from dictionary
df = pd.DataFrame(data)
# Calculate mean, maximum and minimum for "temperature"
print("Mean temperature:", df["temperature"].mean())
print("Maximum temperature:", df["temperature"].max())
print("Minimum temperature:", df["temperature"].min())

import pandas as pd
path = ("/content/people.csv")
#define desired columns
desiredColumns = ["First Name", "Sex", "Email", "Phone", "Job Title"]
#read the CSV, skipping rows 1 and 5, and selecting only desired columns
df = pd.read_csv(path, skiprows=[1, 5], usecols=desiredColumns)
#setting "Sex" and "Job Title" as index columns
df.set_index(["Sex", "Job Title"], inplace=True)
#exporting the dataFrame as "NewPeople.csv"
df.to_csv("NewPeople.csv")
print("Data successfully exported!")

import pandas as pd
path = ("/content/SampleWork.xlsx")
#read sheet 1, skip row 2, select first and last columns, use row 2 as header
df = pd.read_excel(path, sheet_name=0, skiprows=1, usecols=[0, -1], header=1)
#exporting the processed data as a new sheet named "NewSheet" within the same Excel file
writer = pd.ExcelWriter(file_path, engine='openpyxl', mode='a')
df.to_excel(writer, sheet_name='New_Sheet', index=False)
writer.save()
print("Data successfully exported!")

import pandas as pd
data = {
    "Name": ["Sonia", "Bilal", "Hifza", "Kabir", "jazim"],
    "Age": [27, 24, 22, 32, 23],
    "Address": ["Lahore", "Karachi", "Sialkot", "Peshawar", "Ihr"],
    "Qualification": ["Msc", "MA", "MCA", "Phd", "bsc"]
}
AICP_DF = pd.DataFrame(data)
#select 'Name', 'Qualification' columns and save to df1
df1 = AICP_DF[['Name', 'Qualification']]
#adding a new column "Height" with values [5.1, 6.2, 5.1, 5.2, 5.1]
AICP_DF["Height"] = [5.1, 6.2, 5.1, 5.2, 5.1]
#set column "Name" as the index column
AICP_DF.set_index("Name", inplace=True)
# retrieve row with index "Hifza"
hifaza_row = AICP_DF.loc["Hifza"]
#retrieve row with index 3
row_3 = AICP_DF.iloc[3]
#drop row with index "Bilal"
AICP_DF.drop("Bilal", inplace=True)
print("df1:")
print(df1)
print("AICP_DF with new column:")
print(AICP_DF)
print("Row with index 'Hifza':")
print(hifaza_row)
print("Row with index 3:")
print(row_3)
print("AICP_DF after dropping 'Bilal':")
print(AICP_DF)